#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ACTION="${1:-plan}"

: "${BASE_CONFIG:?Set BASE_CONFIG to an existing experiment env file}"
: "${MATRIX_NAME:?Set MATRIX_NAME to a unique experiment family name}"
: "${DRAFT_MODEL:?Set DRAFT_MODEL to the exported SGLang draft directory}"
: "${VAL_T0_DATA:?Set VAL_T0_DATA to the frozen validation request JSONL}"
: "${TRAIN_T0_DATA:?Set TRAIN_T0_DATA to the frozen train request JSONL}"

[[ -f "${BASE_CONFIG}" ]] || { echo "BASE_CONFIG不存在: ${BASE_CONFIG}" >&2; exit 2; }
[[ -d "${DRAFT_MODEL}" ]] || { echo "DRAFT_MODEL不存在: ${DRAFT_MODEL}" >&2; exit 2; }
[[ -f "${VAL_T0_DATA}" ]] || { echo "VAL_T0_DATA不存在: ${VAL_T0_DATA}" >&2; exit 2; }
[[ -f "${TRAIN_T0_DATA}" ]] || { echo "TRAIN_T0_DATA不存在: ${TRAIN_T0_DATA}" >&2; exit 2; }

SPLITS="${SPLITS:-val train}"
TREES="${TREES:-s2k2d4:2:2:4}"
EVAL_MODE="${EVAL_MODE:-formal}"
EVAL_GPU_DEVICES="${EVAL_GPU_DEVICES:-6,7}"
EVAL_TP_SIZE="${EVAL_TP_SIZE:-2}"
EVAL_PORT_BASE="${EVAL_PORT_BASE:-34600}"
EVAL_LIMIT="${EVAL_LIMIT:-500}"
EVAL_SAMPLE_SEED="${EVAL_SAMPLE_SEED:-20260805}"
EVAL_CONCURRENCIES="${EVAL_CONCURRENCIES:-1}"
EVAL_WARMUP="${EVAL_WARMUP:-8}"
EVAL_OVERWRITE="${EVAL_OVERWRITE:-0}"
GENERATED_ROOT="${GENERATED_ROOT:-${REPO_ROOT}/artifacts/eval-matrix/${MATRIX_NAME}}"

case "${EVAL_MODE}" in
  formal)
    REQUEST_DIAGNOSTICS=0
    DECODE_LOG_INTERVAL="${EVAL_DECODE_LOG_INTERVAL:-40}"
    ;;
  diagnostic)
    REQUEST_DIAGNOSTICS=1
    DECODE_LOG_INTERVAL=1
    [[ "${EVAL_CONCURRENCIES}" == "1" ]] || {
      echo "diagnostic模式只允许EVAL_CONCURRENCIES=1" >&2
      exit 2
    }
    ;;
  *)
    echo "EVAL_MODE必须是formal或diagnostic" >&2
    exit 2
    ;;
esac

case "${ACTION}" in
  plan|run) ;;
  *) echo "用法: $0 {plan|run}" >&2; exit 2 ;;
esac

mkdir -p "${GENERATED_ROOT}"
read -r -a split_items <<< "${SPLITS}"
read -r -a tree_items <<< "${TREES}"

index=0
for split in "${split_items[@]}"; do
  case "${split}" in
    val) input="${VAL_T0_DATA}" ;;
    train) input="${TRAIN_T0_DATA}" ;;
    *) echo "未知split: ${split}; 只支持val/train" >&2; exit 2 ;;
  esac

  for tree in "${tree_items[@]}"; do
    IFS=: read -r tag steps topk draft_tokens <<< "${tree}"
    [[ -n "${tag}" && -n "${steps}" && -n "${topk}" && -n "${draft_tokens}" ]] || {
      echo "树格式错误: ${tree}; 应为tag:steps:topk:draft_tokens" >&2
      exit 2
    }

    experiment="${MATRIX_NAME}-${split}-${tag}-${EVAL_MODE}"
    config="${GENERATED_ROOT}/${experiment}.env"
    port=$((EVAL_PORT_BASE + index))
    index=$((index + 1))

    cp "${BASE_CONFIG}" "${config}"
    cat >> "${config}" <<EOF

# Generated by scripts/06_evaluate_matrix.sh. Last assignment wins.
EXPERIMENT_NAME=${experiment}
VAL_DATA=${input}
EVAL_DRAFT_MODEL=${DRAFT_MODEL}
EVAL_GPU_DEVICES="${EVAL_GPU_DEVICES}"
EVAL_TP_SIZE=${EVAL_TP_SIZE}
EVAL_PORT=${port}
SPEC_NUM_STEPS=${steps}
SPEC_TOPK=${topk}
SPEC_DRAFT_TOKENS=${draft_tokens}
EVAL_CONCURRENCIES="${EVAL_CONCURRENCIES}"
EVAL_LIMIT=${EVAL_LIMIT}
EVAL_WARMUP=${EVAL_WARMUP}
EVAL_SAMPLE_SEED=${EVAL_SAMPLE_SEED}
EVAL_DECODE_LOG_INTERVAL=${DECODE_LOG_INTERVAL}
EVAL_REQUEST_DIAGNOSTICS=${REQUEST_DIAGNOSTICS}
EOF

    echo "============================================================"
    echo "实验: ${experiment}"
    echo "Split/Input: ${split} / ${input}"
    echo "Tree: ${steps}/${topk}/${draft_tokens}"
    echo "Mode: ${EVAL_MODE}; GPU: ${EVAL_GPU_DEVICES}; port: ${port}"
    echo "Config: ${config}"

    if [[ "${ACTION}" == run ]]; then
      LINGBAO_CONFIG="${config}" \
      EVAL_OVERWRITE="${EVAL_OVERWRITE}" \
      bash "${REPO_ROOT}/scripts/05_evaluate.sh" all validation
    fi
  done
done

if [[ "${ACTION}" == plan ]]; then
  echo
  echo "仅生成并检查配置；确认后把plan改为run。"
fi
